### ISSUE TITLE
Issue with Not Equal node in 5.1

### ISSUE THREAD

**Issue by RedCraft86** [Naotsun19B/PulldownBuilder#3]
I'm putting this issue here because Epic Games decided to age restrict the Reviews and Questions in the Marketplace for some reason.

Anyway, here's the issue, in Unreal 5.1, if I spawn a generic Not Equal node and connect something to it, it converts it into a the Pulldown Builder's Not Equal node, resulting in the code basically breaking. This is more of just a minor inconvenience since I can just use an equal node and flip the result but It's still pretty annoying.

Video: 
https://user-images.githubusercontent.com/67089499/209453194-57d7ef08-c53f-4811-986c-bddbf308d81f.mp4

**Comment by Naotsun19B** [comment]
I apologize for the delay.
I have fixed the problem with the not equal node that you reported to me in the update of version 1.9.
I will notify you on the Marketplace Questions side when the Marketplace update is finished.
