### ISSUE TITLE
C++ created pulldown structs no longer display as a combo box in the details panel

### ISSUE THREAD

**Issue by RedCraft86** [Naotsun19B/PulldownBuilder#4]
I had this issue on both the UE 5.1 and 5.2 versions of the plugin (unsure of the rest)
It seems like the latest update broke them?

The following images were from a test project in UE 5.2 that I made to verify that it didn't work

![Screenshot 2023-06-10 212610](https://github.com/Naotsun19B/PulldownBuilder/assets/67089499/7332acd8-4e49-4b6a-b000-b12fe12a053d)
![Screenshot 2023-06-10 212700](https://github.com/Naotsun19B/PulldownBuilder/assets/67089499/028d74f3-56f0-4803-a91b-5d1fb16de879)
![Screenshot 2023-06-10 212731](https://github.com/Naotsun19B/PulldownBuilder/assets/67089499/cbb9c91e-5406-405e-be11-6f67699fbb5b)

**Comment by RedCraft86** [comment]
I checked the logs and they're pretty weird too
It's like, flipped around, its treating None like a valid struct and not seeing the rest

![Screenshot 2023-06-10 221308](https://github.com/Naotsun19B/PulldownBuilder/assets/67089499/09f19f46-059f-4a47-92a6-d127eebe7141)

**Comment by Naotsun19B** [comment]
I apologize for the inconvenience. 
I have submitted an update to the marketplace that includes a fix for that bug and are waiting for review. 
I expect the update to be available on the marketplace soon, but if you are in a hurry, please get the latest plugin from Github.

**Comment by RedCraft86** [comment]
Tested out version 2.2 (Github build). The issue is solved!
